# syntax=docker/dockerfile:1
FROM golang:1.24-alpine AS build
WORKDIR /app
COPY . .
RUN go build -o /app/example ./cmd/example-api

FROM gcr.io/distroless/base-debian12
COPY --from=build /app/example /example
ENV HTTP_ADDR=:8443 GRPC_ADDR=:50051
EXPOSE 8443 50051
ENTRYPOINT ["/example"]
